import React, { FC } from 'react';
import Head from 'next/head';
import { Box } from '@mui/material';
import TemporariDrawer from '../common/ui/TemporariDrawer';
import { Navbar } from '../common';

type Props = {
	title?: string;
	children: React.ReactNode | React.ReactNode[];
};

const Layout: FC<Props> = ({ title, children }) => {
	return (
		<Box>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='initial-scale=1, width=device-width' />
				<title>{title}</title>
			</Head>
			<Navbar />
			<TemporariDrawer />
			<Box px={20}>{children}</Box>
		</Box>
	);
};

export default Layout;
