import Head from 'next/head';

import { Typography } from '@mui/material';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='viewport' content='initial-scale=1, width=device-width' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Typography fontSize={30}>Hello word</Typography>
		</div>
	);
}
